server:
  port: 8080

spring:
  application:
    name: ead-api-gateway
  cloud:
    gateway:
      routes:
        - id: userauth-service
          uri: lb://EAD-USERAUTH-SERVICE
          predicates:
            - Path=/ead-userauth/**
        - id: course-service
          uri: lb://EAD-COURSE-SERVICE
          predicates:
            - Path=/ead-course/**

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost

